driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
  - name: centos-7.2
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: wheezy:7

suites:
  - name: default
    run_list:
      - recipe[openvpnas::default]
    attributes:
      openvpnas:
        company_name: company_name
