driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[openvpnas::default]
    attributes:
      openvpnas:
        company_name: company_name
